# Generated by Django 6.1 on 2026-09-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeracaoSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('GERADO', 'Gerado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('arquivo_saida', models.CharField(blank=True, max_length=255, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('slides', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_geracao', models.DateTimeField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('avisos', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Geração de Slide',
                'verbose_name_plural': 'Gerações de Slides',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
