# Generated by Django 6.1 on 2026-09-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('usuario_id', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('materia', models.CharField(blank=True, max_length=255, null=True)),
                ('curso', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('processando', 'Processando'), ('ativo', 'Ativo'), ('arquivado', 'Arquivado'), ('excluido', 'Excluído')], default='criado', max_length=20)),
                ('conteudo', models.JSONField(blank=True, null=True)),
                ('arquivo_url', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('sincronizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSupabase',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário Supabase',
                'verbose_name_plural': 'Usuários Supabase',
            },
        ),
    ]
