# Generated by Django 6.1 on 2026-09-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_slide_usuariosupabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso_id', models.IntegerField(help_text='ID da referência de curso')),
                ('materia_id', models.IntegerField(help_text='ID da referência de materia')),
                ('descricao', models.CharField(help_text='Nome/descrição da ementa', max_length=255)),
                ('conteudo', models.JSONField(blank=True, help_text='Conteúdo markdown da ementa armazenado como JSON', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ementa',
                'verbose_name_plural': 'Ementas',
                'db_table': 'ementas',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['curso_id'], name='ementas_curso_i_11ec95_idx'), models.Index(fields=['materia_id'], name='ementas_materia_9bb8a7_idx'), models.Index(fields=['-data_criacao'], name='ementas_data_cr_ebb685_idx')],
                'unique_together': {('curso_id', 'materia_id')},
            },
        ),
    ]
