INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (2, 1, '100 pedidos por mês', 1, 4);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (3, 1, '100MB de Banco de Dados', 1, 2);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (4, 1, '1 GB de File Storage', 0, 5);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (13, 4, '100MB de Banco de Dados', 0, 2);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (17, 5, '1 GB de File Storage', 0, 5);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (21, 1, '50 Usuários Ativos por mês', 1, 1);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (24, 4, '50 Usuários Ativos por mês', 0, 1);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (25, 5, '50 Usuários Ativos por mês', 1, 1);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (26, 1, '100 Usuários Ativos por mês', 0, 6);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (30, 5, '100 Usuários Ativos por mês', 0, 6);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (7, 2, '100MB de Banco de Dados', 1, 2);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (5, 2, '1 GB de File Storage', 1, 5);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (8, 2, '10 pedidos por dia', 1, 3);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (9, 2, '100 pedidos por mês', 1, 4);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (22, 2, '50 Usuários Ativos por mês', 1, 1);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (27, 2, '100 Usuários Ativos por mês', 1, 6);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (15, 4, '100 pedidos por mês', 1, 4);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (14, 4, '10 pedidos por dia', 1, 3);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (16, 4, '1 GB de File Storage', 1, 5);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (29, 4, '100 Usuários Ativos por mês', 1, 6);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (20, 5, '100MB de Banco de Dados', 1, 2);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (19, 5, '100 pedidos por mês', 1, 4);
INSERT INTO "planfeature" ("id", "plan_id", "descricao", "ativo", "feature_id") VALUES (18, 5, '10 pedidos por dia', 1, 3);